name: trendup_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  shared_preferences: ^2.5.3
  go_router: ^16.2.5
  dio: ^5.9.0
  lottie: ^3.3.2
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  firebase_storage: ^13.0.4
  applovin_max: ^4.6.0
  google_mobile_ads: ^6.0.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg